# Generated by Django 6.0.6 on 2026-07-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField(null=True)),
                ('outdoor_seating', models.BooleanField(null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
